### ISSUE TITLE
[Safari on iOS] Download fails if popups are disabled

### ISSUE THREAD

**Issue by runar** [johnculviner/jquery.fileDownload#100]
If I disable popups in Safari on iOS (tested on both iOS 7 and 9), file downloads fails on my site. If I enable popups, a dialog appears asking me if I want to open the popup or not.

With popups disabled, the following appears in the console:

```
TypeError: undefined is not an object (evaluating 'downloadWindow.document’)
```

Which referrers to line 263 in `jquery.fileDownload.js`. Below are the relevant lines (line 263 is the line in the middle):

```javascript
if (isIos || isAndroid) {

                    downloadWindow = window.open(fileUrl);
                    downloadWindow.document.title = settings.popupWindowTitle;
                    window.focus();

                }
```

The demo pages works just fine, even with popups disabled, so I am not sure what I have done wrong. This also only happens on iOS.

Any suggestions?

**Comment by uiyuvi** [comment]
This issue happens to me .It really blocks user to download pdf if user doesn't enable allow popup blocker

**Comment by jakeholland** [comment]
Same problem showing up for me now. Did you guys happen to find a workaround.

**Comment by johnculviner** [comment]
popup blocker isn't enabled by default so its probably not a big deal.... i dont think safari is honoring JS spec here by blocking that since its based on user interaction...

**Comment by jakeholland** [comment]
I figured out my issue... Might be the same for others. I was triggering the download from a "<button>" changing to and '<a>' and adding 'href="javascript:void(0)"' allowed it to work.

**Comment by johnculviner** [comment]
Yeah it *must* be in the same stack as a javascript click event not an implicit eval or setTimeout etc. Thats when popupblockers come in. I'm gonna close for now since this is a bug w/ the browser and not the plugin if it is doing otherwise since this is standard behavior
