### ISSUE TITLE
cannot load "jquery-file-download" module

### ISSUE THREAD

**Issue by prabhakarreddy1234** [johnculviner/jquery.fileDownload#111]
installed module through NPM.

require("jquery-file-download") is throwing exception

Module not found: Error: Cannot resolve module 'jquery-file-download'

**Comment by johnculviner** [comment]
are you using browserify or what? require('jquery-file-download') is not going to work because this is a client side thing NOT a node plugin

**Comment by johnculviner** [comment]
if you need it to work with browserify or webpack an index.js will need to be added

**Comment by prabhakarreddy1234** [comment]
Thanks, I am working with Webpack. is it possible for you to add index.js.

**Comment by johnculviner** [comment]
i added it, not sure how it works w/ webpack or not. if it doesn't work still feel free to send me a PR w/ what you need to to get it to work

**Comment by prabhakarreddy1234** [comment]
Can you push that to NPM please.. i will test it and let u know the outcome.

**Comment by prabhakarreddy1234** [comment]
I added index.js and tried to load but it's giving exception jQuery is not defined. "Uncaught ReferenceError: jQuery is not defined" It has some conflict with jQuery it seems.  If i commented out jquery-file-download stuff then everything works fine.

**Comment by johnculviner** [comment]
hmm not sure, haven't used browserify. latest is published!

**Comment by prabhakarreddy1234** [comment]
consumed and tested. getting same error of jQuery not defined. I am also using jQuery.Cookie node package .  It works fine. I compared this package with your package. But i don't see any major differences.

**Comment by johnculviner** [comment]
feel free to try messing w/ it in node_modules locally and see if you can get it to work. ill merge the PR if you figure out something. good luck!

**Comment by prabhakarreddy1234** [comment]
I fixed it in the webpack configuration file. 

  plugins: [
         new webpack.ProvidePlugin({
             $: "jquery",
             jQuery: "jquery",
             "window.jQuery": "jquery"
         })
    ]
Now  file download is working fine.

Thanks....

**Comment by johnculviner** [comment]
sounds good!
