### ISSUE TITLE
iframes are not removed from the body element

### ISSUE THREAD

**Issue by danielpacak** [johnculviner/jquery.fileDownload#112]
Any reason why you commented out the iframe removal code? Does it mean that we should reopen #24?

```js
//iframe cleanup appears to randomly cause the download to fail
//not doing it seems better than failure...
//if ($iframe) {
//    $iframe.remove();
//}
```

**Comment by ealfonsov89** [comment]
not

2015-11-12 7:28 GMT-08:00 Daniel Pacak <notifications@github.com>:

**Comment by johnculviner** [comment]
If I remember properly sometimes the DL would fail. I don't think having the iframe there really causes any problems does it?

**Comment by ealfonsov89** [comment]
hi, i fix all mi problems removing the copy cookie at the end of a copy, i think like you.

**Comment by danielpacak** [comment]
Well, @johnculviner, indeed this is not a big deal. However, in my app (and probably majority of modern web apps) a user may stay on the same index.html for a while without the whole page refresh. If she downloads a lot then the HTML DOM grows which can be problematic at some point. That's why I'd vote for removing useless iframes.

**Comment by johnculviner** [comment]
Yeah I been doing mostly SPAs for the last 5 years or so extra junk in the DOM not good! Totally understand your thought here but if its any conciliation an empty iframe shouldn't use too many resources and I'd rather err on the side of it always working

**Comment by danielpacak** [comment]
All right. Thanks for clarifications. I got your point. Hence, I'm closing this issue.
