### ISSUE TITLE
Does not work on iOS Safari

### ISSUE THREAD

**Issue by elliotatRetireup** [johnculviner/jquery.fileDownload#115]
window.open() doesn't work on iOS with popups disabled.

If you enable popups it just opens a window and pastes text from the file into the window.

**Comment by johnculviner** [comment]
works fine on my iPhone (iOS 9) when i use the demo site:

https://jqueryfiledownload.apphb.com/

Let me know otherwise and I can re-open but my suspicion is you might have an issue with your code

**Comment by azzimuth** [comment]
Does not work on iOS 10.2.1 with fileDownlad version 1.4.0.
