### ISSUE TITLE
success event cannot be catched when use download manager

### ISSUE THREAD

**Issue by thanhhungtn1** [johnculviner/jquery.fileDownload#119]
I added an option when success to popup a message when it's success download.
But it only popup when download by the browser and not popup when I use internet download manager. 
Is there anything wrong?

**Comment by johnculviner** [comment]
Yeah an internet download manager probably wouldn't work with this. I doubt more than .01% of your clientele use one of those (and besides if they do they can likely expect weird behavior on many websites). This won't and can't be supported.
