### ISSUE TITLE
failCallback not invoked in latest Chrome and Safari

### ISSUE THREAD

**Issue by metmajer** [johnculviner/jquery.fileDownload#12]
Hi, thanks for your helpful plugin. Unfortunately, the failCallback is not executed on latest Chrome and Safari browsers (tested on Mac) if the server responds with a HTTP 400 error code. However, the callback is executed in Firefox. Can you think of a quick fix for this?

**Comment by akotlar** [comment]
Just wanted to let you you know john that you were exactly right; the solution is to send some content with the 400 response.

**Comment by runar** [comment]
I’m experiencing this problem and I haven’t been able to solve it. Below are the details of the response that should trigger `failCallback`:

Status code:
```
400 Bad Request
```

Headers:
```
Connection: keep-alive
Content-Type: text/html; charset=utf-8
Date: Mon, 22 Jun 2015 20:59:34 GMT
Server: nginx/1.8.0
Transfer-Encoding: chunked
X-Powered-By: PHP/5.6.10
```

Content:
```
Bad Request
```

I have tried with other status codes (the 400 and 500 range) as well as no content and more content, but nothing makes any difference.

Any ideas?

**Comment by runar** [comment]
Update: I made it work by setting the cookie to `false`:

```php
header( 'Set-Cookie: fileDownload=false; path=/' );
```

Is this necessary?
