### ISSUE TITLE
Resource interpreted as Document but transferred with MIME type audio/mpeg

### ISSUE THREAD

**Issue by carlos-andres** [johnculviner/jquery.fileDownload#127]
Good Day, 

good morning I tried to make the implementation of downloads, adding the cookie and using the basic code, in addition I have the full path of the file I'm trying to download as it is not hosted on the same server because is  a heavy resource

the code works but in adition showme the subject message.. and my question is how to change MIME to force download it?.

Thanks.

![image](https://cloud.githubusercontent.com/assets/5489747/16774449/90ddafe0-4821-11e6-8cbc-bbea9721bd09.png)

**Comment by johnculviner** [comment]
You will need to do that on the server http://stackoverflow.com/questions/1395151/content-dispositionwhat-are-the-differences-between-inline-and-attachment
