### ISSUE TITLE
successCallback not working

### ISSUE THREAD

**Issue by torp3d0** [johnculviner/jquery.fileDownload#129]
![image](https://cloud.githubusercontent.com/assets/7699793/17732435/54bfd3d6-64a4-11e6-8352-3353db5bf0c0.png)

i was able to add the cookie but still successCallback not working.

i try to debug log the document.cookie the value is empty. 

but the repose already said has cookie

**Comment by johnculviner** [comment]
Is this demo working for you? http://jqueryfiledownload.apphb.com/

Also are you serving up the file from the same domain that you see in the address bar?

**Comment by berthojoris** [comment]
I have a same issue...Link to download, and page when I try to download its same domain...

**Comment by alejoar** [comment]
I had this issue.

Solved by adding this header:
`Set-Cookie: fileDownload=true; path=/`

**Comment by johnculviner** [comment]
Make sure you follow this and if it still doesn't work you may have found a bug (let me know and i'll re-open https://github.com/johnculviner/jquery.fileDownload#common-questions-and-answers)

**Comment by solaechea** [comment]
When you set the cookie, you should set HttpOnly property to false!
