### ISSUE TITLE
Allow download to occur in new tab 

### ISSUE THREAD

**Issue by diptesh2007** [johnculviner/jquery.fileDownload#136]
Hi,
I am using IE-11 and want to download to take place in a new tab/window through GET request.
Is there an provision to download the file in a new tab?

**Comment by johnculviner** [comment]
```
<a href="my_file_url" target="_blank">Click here to download the file</a>
```
or
```
window.open("my_file_url"....
```
would probably be more up your alley

**Comment by diptesh2007** [comment]
I am using the file download api such as:
`function downloadFile(){`
      `$.fileDownload(url,`
                  `{`
                      `successCallback: function(url) {`
                           `// custom operation`
		  `},`
                  `......`
`)}`

Is it possible to pass some options inside $.fileDownload() to open a new tab?

**Comment by johnculviner** [comment]
Not currently. If you want a new tab try make the new tab and invoke jquery file download on the new tab (assuming you want the modal and/or callback support on the new tab?)
