### ISSUE TITLE
Support for <meta name="apple-mobile-web-app-capable" content="yes">

### ISSUE THREAD

**Issue by 14skywalker** [johnculviner/jquery.fileDownload#137]
Hi John,

I am getting errors when using the `apple-mobile-web-app-capable` option and saving the page as safari webclip on an iPad. Safari/ios now removes the tabs, and should open all new/external links in the safari browser. Would be nice it this would work.

Best regards,
Jeroen

**Comment by johnculviner** [comment]
Your situation seems pretty specific but I'd definitely be happy to accept a PR if you can come up with a fix for it

**Comment by 14skywalker** [comment]
Thanks, John. debugging to find out what is really happening is a pain, but I'll see what I can do ;-)

**Comment by 14skywalker** [comment]
Hi John, I tried to fix this but it seems not possible at the moment. See [http://stackoverflow.com/questions/7930001/force-link-to-open-in-mobile-safari-from-a-web-app-with-javascript#answer-8833025](url). Brgrds.

**Comment by johnculviner** [comment]
eek, bummer. yeah mobile safari is a pain since apple likes to make their own standards (big surprise they are the new MS right?)
