### ISSUE TITLE
Refused to display

### ISSUE THREAD

**Issue by BenjaminHorn** [johnculviner/jquery.fileDownload#138]
I generate an PDF and send it back from the server.
Everything works fine (the pdf downloads), except I am getting in the console

> Refused to display 'http://localhost:30022/api/...' in a frame because it set 'X-Frame-Options' to 'SAMEORIGIN'.

I my app runs on http://localhost:4200, same domain but different port.
'X-Frame-Options' orginally was 'DENY', I changed it 'SAMEORIGIN'

(I think) because of this, the callbacks are messed up and I have to implement .fail

```
      Ember.$.fileDownload(url)
        .done()
        .fail(() => this.set('generatingPDF', false) );
```

**Comment by johnculviner** [comment]
Either of these answer your question?

https://github.com/johnculviner/jquery.fileDownload#common-questions-and-answers
