### ISSUE TITLE
jquery filedownlod successcallback not working with secure header

### ISSUE THREAD

**Issue by sushant4nt** [johnculviner/jquery.fileDownload#139]
If I set the header as secure (_Set-Cookie: Secure_) then successcallback doesn't work.

Is there a way I can make it work without removing secure header?

**Comment by johnculviner** [comment]
Nope, secure cookies mean they are only accessible by the server and not by JavaScript. this might work for you if you can accept so so browser compatibility https://github.com/eligrey/FileSaver.js/
