### ISSUE TITLE
No error code of http response on failCallback if no exception

### ISSUE THREAD

**Issue by cmichal** [johnculviner/jquery.fileDownload#146]
Hi,

I would like to differentiate error message displayed to the user based on http response code. If there is no exception in failCallback I get only responseHtml and url but not the code. Can this be added?

thanks
mC

**Comment by johnculviner** [comment]
This library uses an iframe so this isn't possible. depending on what browsers you need to support https://github.com/eligrey/FileSaver.js/ might fix your issue
