### ISSUE TITLE
Problem downloading via POST on iOS Safari

### ISSUE THREAD

**Issue by tkaragiannis92** [johnculviner/jquery.fileDownload#148]
From an iPhone 6s device web inspector logs, connected via usb to a MacBook and enabled Safari's Develop menu, I get the following `failCallback` error:
`SecurityError (DOM Exception 18): Sandbox access violation: Blocked a frame at "http://example.com" from accessing a frame at "http://example.com". The frame being accessed is sandboxed and lacks the "allow-same-origin" flag.`

**Comment by johnculviner** [comment]
The demo site works on my iPhone, does it for you? You cannot use file download cross origin and have it work.

**Comment by tkaragiannis92** [comment]
As you see in the description provided above, it says `Blocked a frame at "http://example.com" from accessing a frame at "http://example.com"` so it is NOT cross origin. Its the SAME origin.
Correct me if I am wrong, but I think you've only provided examples in your demo site via GET but not POST method.

**Comment by johnculviner** [comment]
https://jqueryfiledownload.apphb.com/

3rd one down 

**POST Request: Simple rich user experience - jquery.fileDownload.js & jQuery UI Dialog**

Please check if this works in your browser situation and let me know if it doesn't and we can discuss further. Cheers, John
