### ISSUE TITLE
Success msg alert before actual pdf download completed

### ISSUE THREAD

**Issue by bai35304823** [johnculviner/jquery.fileDownload#151]
Currently , I use jquery fileDownload plugin to download multiple pdf that in a list page, which every single hyperlink can download one pdf file.
When i click 1st link, every thing occured ok, but when click 2nd or other link, success msg alert before actual pdf download completed. It confused me a few days...
Finally, i find the reason and got a way to resolve the problem.

We can check source code in  jquery.filedownload.js, when document.cookie contains value 'fileDownload=true', it will pop up success msg. The key is when finish the 1st download, the cookie not expired!!! So when you click second ,third link,msg alert before download.
I tried set cookie 's  maxAge ,but it still same error.. 

The thing we do is every download we need create a unique cookie.

Thanks  http://gruffcode.com/2010/10/28/detecting-the-file-download-dialog-in-the-browser/,
We can generating a token value using the current timestamp as the value of 'filedownload', This token can really be any arbitrary string value, but we do want to try and make it unique per request coming from the same browser, and using the timestamp is a pretty easy way to do this. We take that token and add it to the form within that hidden field that we created. This will ensure that the token value gets submitted up to the server (more on this later).

**Comment by johnculviner** [comment]
Hey there, make sure you are doing it exactly like the demo since there are many files on that page and I do not have the issue. Let me know if you have found a bug but I think you might just need to change your code: http://jqueryfiledownload.apphb.com/
