### ISSUE TITLE
Chrome 64 issue 

### ISSUE THREAD

**Issue by katomic** [johnculviner/jquery.fileDownload#153]
The callback is fired immediately in Chrome 64 instead of when the download starts. I am using a FileResult instead of filepathresult. Could that be the cause?

**Comment by lolsoftware** [comment]
I confirm that this issue still exists in v1.4.5 in Chrome 67.

If that helps, below is how I use jquery.fileDownload:

        var $preparingFileModal = $("#preparing-file-modal");
        $preparingFileModal.dialog({ modal: true });

        $.fileDownload(url, {
            successCallback: function (url) {
                $preparingFileModal.dialog('close');
            },
            failCallback: function (responseHtml, url) {
                $preparingFileModal.dialog('close');
                $("#error-modal").dialog({ modal: true });
            }
        });

**Comment by johnculviner** [comment]
Just tried all the examples on this page in latest chrome and it seems to be working fine http://jqueryfiledownload.apphb.com/
Make sure to heed this: https://github.com/johnculviner/jquery.fileDownload#note---you-must-also-write-a-cookie-in-conjunction-with-using-this-plugin-as-mentioned-in-the-orignal-post

Let me know if you still have issues but it appears to be working as documented for me on my end!

**Comment by lolsoftware** [comment]
I restarted the computer and it works fine now.

**Comment by joshuapinter** [comment]
@johnculviner You're linking to _another_ link. Is this the section on the original post that you're tell us to "heed"? 

>An iframe and cookie
>What?! I have to rely on Web .1 technology to make my Web 2.0 Ajax application user friendly? Turns out this is the magic bullet combination to work around normal limitations of file downloads, here’s how:
>
>iframe
>
>An iframe (which is generally a mortal sin of modern web development) can exist in a DOM but in most respects is treated like an entirely different window. By dynamically inserting a hidden iframe into the DOM and setting its location to the desired file path we can initiate a file download just like it was occurring in the main application window. This directly gets us around one of the nasties of file downloads – if an error occurs the user has now been forced off of the page they were on (which may contain an Ajax application like Gmail) to see an ugly error message.
>
>Like a normal file download in the main window an iframe will never fill with content when a successful file download occurs. It simply contains an empty DOM. Well how do we detect what is going on if nothing happens when the file download is successful. Well this is where the cookie comes in:
>
>cookie + iframe
>
>Since the creation of cookies exists in HTTP headers, which is standard fare for all web requests and responses, we can actually write a cookie to indicate that a file download has been initiated properly (instead of an error page). The response from the web server will now look something like this:
>
>Content-Disposition: attachment; filename=Report0.pdf
>Set-Cookie: fileDownload=true; path=/
> 
>While we can’t directly tell if a file download has occurred we can check for the existence of a cookie which is exactly how jQuery File Download works. Once a download is initiated on the iframe a configurable duration poll of cookies and the iframe contents occurs. If the iframe fills with contents then we know a file download has occurred (in most cases, make sure to set a MIME type!). If the cookie gets written then we know to stop polling and kill the iframe because the file download dialog/ribbon has been displayed.

**Comment by johnculviner** [comment]
@joshuapinter  again I look forward to a pull request rather than you trolling closed issues on my plugin that don't look quite like how you want.

**Comment by joshuapinter** [comment]
@johnculviner No disrespect or trolling. I know how tiring open source work can be. I use and value your plugin, so thanks so much for writing it and releasing it to the world. I must have hit one too many gumption traps that day and my patience meter bottomed out. I think the README could be updated for clarity and the responsibility equally lies with the open source community, including myself, to do. Thanks again.
