### ISSUE TITLE
Chrome version 70.0.3538.77 64 bits not working when latin chars

### ISSUE THREAD

**Issue by CarlosHBP** [johnculviner/jquery.fileDownload#160]
Hi,

After Chrome update 70.0.3538.77 64 bits not working with fileDownload:

Before update:
nomtab=Visualização
Request.Form: nomtab=Visualiza%u00e7%u00e3o

After update:
nomtab=VisualizaÃ§Ã£o
Request.Form: nomtab=Visualiza%u00c3%u00a7%u00c3%u00a3o

When not using fileDownload, Chrome works.
Edge works fine with fileDownload.

Any suggestions?!

Thanks!

**Comment by CarlosHBP** [comment]
It's working doing that way:

I already changed the target and the action of the form to an iframe:

    var $frm_go = $(frm_go);
    $frm_go.attr("target", "ifr_export");
    $frm_go.attr("action", str_site + "/admin/includes/export/export.aspx");
    $frm_go.submit();

Submit function:

    $(document.forms["frm_app_generate"]).off('submit').on("submit", function (e)
    {
        var $this = $(this);
        $.fileDownload($this.attr('action'), {

            failCallback: function (responseHtml, url)
            {
                //...
            },
            successCallback: function (url)
            {
                //...
            },
            httpMethod: "POST",
            formName: "frm_app_generate",
            iframeId: "ifr_export",
            data: $this.serialize()
        });
        e.preventDefault(); //otherwise a normal form submit would occur
    });

Inside fileDownload.js:

Added parameters inside extend:

            formName: 0,
            iframeId: null,

And then  just call the submit again:

        /*
        if (httpMethodUpper === "GET") {
        ...
            $form.submit();
        }
        */

        $iframe = $("#" + settings.iframeId);
        $form = document.forms[settings.formName];
        $form.submit();

**Comment by johnculviner** [comment]
glad you got it working. it looks like stuff is working on the demo site http://jqueryfiledownload.apphb.com/ too in regard to POSTs on latest chrome for me so I'm going to close this
