### ISSUE TITLE
Download fails on IE 10

### ISSUE THREAD

**Issue by zjumty** [johnculviner/jquery.fileDownload#34]
It works fine before IE 10.
But on IE 10, it will fail at first time of downloading, then be success when retry downloading again.

**Comment by afattahi54** [comment]
In IE you need to reset the response http://stackoverflow.com/questions/28609996/ie-doesnt-download-file-with-jquery-file-download-plugin

**Comment by johnculviner** [comment]
Yeah, this isn't really related to jQueryFileDownload rather than using it with Java. Glad you found a solution though!
