### ISSUE TITLE
"done" function never called

### ISSUE THREAD

**Issue by kain64** [johnculviner/jquery.fileDownload#76]
the fileDownload cookie installed with java code:
 ResponseBuilder ok = Response.ok(value);
        ok.header("Content-Disposition", "attachment; filename="ololo.zip")
                .header("Set-Cookie","fileDownload=true; path=/")
            .header("Cache-Control", "max-age=60, must-revalidate");
http://snag.gy/97In5.jpg

**Comment by ShangXinbo** [comment]
I  wonder that why is required set server code like header("Set-Cookie","fileDownload=true; path=/")?

**Comment by johnculviner** [comment]
The cookie is the only way to detect reliably/cross browser that a file download has started which causes the callback to get fired. If you can required newer browsers/ not safari you could give this a try for a better experience https://github.com/eligrey/FileSaver.js/
