### ISSUE TITLE
FIle download complete hides all iframes on the page

### ISSUE THREAD

**Issue by lharkleroad** [johnculviner/jquery.fileDownload#77]
There is a bug that causes all iframes on the page to be hidden when the file download has completed. 

```javascript
                //create a temporary iframe that is used to request the fileUrl as a GET request
                $iframe = $("<iframe>")
                    .hide()
                    .prop("src", fileUrl)
                    .appendTo("body");
```

This will hide all iframes, which is a problem when using other plugins such as ckeditor which depends on iframes.

To resolve this, an id should be assigned to the iframe being created above to uniquely identify it for use with this plugin.

```javascript
$iframe = $("<iframe id=\"fileDownload\">")
```

The same thing should be done a little bit further down the script for the following line:
```javascript
                    $iframe = $("<iframe id=\"fileDownload\" style='display: none' src='about:blank'></iframe>").appendTo("body");
```

There may be similar issues for other elements that are being added to the DOM this way such as forms. I have not confirmed this, but the safe thing would be to always add an id to new elements to ensure that other elements of the same type are not affected.

Thanks!

**Comment by lharkleroad** [comment]
After digging much deeper, I discovered that the plugin code is not what is causing the issue. It was very strange, and this was the only thing I could imagine might have caused it at the time, and the proposed fix seemed to work. However, it is actually a bug in Google Chrome.

I am using jQuery tabs on my page. When you download a file and the toolbar showing downloaded files appears at the bottom of the browser window, any iframes that are not currently visible (i.e. in any tab other than the current one) are altered by Chrome to 0px width. Dismissing the toolbar creates the same effect.

Hopefully this will help someone else running into the same issue, at least until Chrome gets fixed.

**Comment by johnculviner** [comment]
Thanks for the heads up! Yeah I was bit confused that this plugin was the culprit directly as it's removing an object from the DOM via a singular reference.
