### ISSUE TITLE
Download fails when try to download files hosted at sourceforge.net

### ISSUE THREAD

**Issue by beni0888** [johnculviner/jquery.fileDownload#81]
When I try to download a file hosted at sourceforge.net, for example http://freefr.dl.sourceforge.net/project/aresgalaxy/aresgalaxy/AresRegular230_081714/aresregular230_installer.exe , the fail callback is triggered and the file is not downloaded.

**Comment by johnculviner** [comment]
https://github.com/johnculviner/jquery.fileDownload#note---you-must-also-write-a-cookie-in-conjunction-with-using-this-plugin-as-mentioned-in-the-orignal-post

**Comment by beni0888** [comment]
But I don't need the cookie because I don't want to show a message or do any other thing when the download finishes. I think the problem is that the server response has a "X-Frame-Options: SAMEORIGIN" http header.

**Comment by johnculviner** [comment]
Then just have a link to the file download or set window.location = 'my download url'. I don't see why you want to use the plugin?

**Comment by beni0888** [comment]
It's because I want the ajax like download behavior and I don't want to add a link to the file download in order not to google bot follow the link. Anyway, thanks for the plugin, it's really usefull ;).

**Comment by johnculviner** [comment]
```
window.location = "some url"
```

will work fine. Yeah it doesn't work cross domain or for servers you can't write a cookie on. best of luck
