### ISSUE TITLE
File encoding

### ISSUE THREAD

**Issue by kglef** [johnculviner/jquery.fileDownload#87]
I have a problem with file encoding, my file is UTF-8 but when downloadet some speciel char like æ, ø and å are not showed correctly, is der allready a fix for setting expected file encoding like: 
Content-Type: text/html; charset=utf-8

**Comment by johnculviner** [comment]
this can't be set for AFAIK since this plugin doesn't (and cannot) do programmatic ajax sever interactions (it just looks like it from the API)

**Comment by johnculviner** [comment]
let me know if you discover otherwise
