### ISSUE TITLE
the library still can't support bower 

### ISSUE THREAD

**Issue by Jinshui** [johnculviner/jquery.fileDownload#91]
Hi all,

I have been using this library for a long time, and it works great for me, thanks all of you for the contribution.
I now moving my project to use the bower to manage dependencies.

However, this library seems still can't support bower, I defined the dependencies as follows in my project:
"dependencies": {
"node-uuid": "1.4.2",
"blueimp-file-upload": "9.9.3",
"jquery.filedownload" : "1.4.1"
},

The error below was shown when I ran 'bower install'
bower jquery.filedownload#1.4.1 ENOTFOUND Package jquery.filedownload not found

I changed the name to 'jquery-file-download', the bower was able to find the package, but found no tag for the version. Below is the output.

bower jquery-file-download#1.4.1 not-cached git://github.com/johnculviner/jquery.fileDownload.git#1.4.1
bower jquery-file-download#1.4.1 resolve git://github.com/johnculviner/jquery.fileDownload.git#1.4.1
bower jquery-file-download#1.4.1 ENORESTARGET No tag found that was able to satisfy 1.4.1

So, please create a tag for that version and change the name to jquery-file-download.

Thanks,
--Jinshui Tang

**Comment by johnculviner** [comment]
Hey, thanks! I added a version for it. Ill update the readme to say to use jquery-file-download when downloading. Thanks
