### ISSUE TITLE
Warning in Google Chrome console when generating pdf/excel document

### ISSUE THREAD

**Issue by shustinho** [johnculviner/jquery.fileDownload#98]
There is a warning in Google Chrome console when generating document: Resource interpreted as Document but transferred with MIME type application/pdf. 

Request Headers:
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8,ru;q=0.6
Cache-Control:max-age=0
Connection:keep-alive
Content-Length:305
Content-Type:application/x-www-form-urlencoded
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.81 Safari/537.36 

Response Headers:
Content-Disposition:attachment; filename=report.pdf
Content-Type:application/pdf;charset=windows-1251
Date:Tue, 02 Jun 2015 13:43:47 GMT
Expires:Thu, 02 Jun 2016 06:50:44 GMT
Server:Apache-Coyote/1.1
Transfer-Encoding:chunked

**Comment by johnculviner** [comment]
Yeah I get that too, it still works though so I think its okay IMO

**Comment by mike192020** [comment]
I get this error also for PDF's. But it will not even try to download. I change the file to download to something else (a non-pdf) but get the error and it still downloads.

Also do you know of a way to suppress this error. I would like to not put the download URL out in the open.

**Comment by johnculviner** [comment]
This isn't a warning in chrome its logged at info. If you are worried about your download URL being logged that's not good because anyone can view it in the chrome debugger or by monitoring http traffic. Would suggest using single use url/token/cookie if you are concerned about URL re-use. The web is not inherently secure: http://johnculviner.com/dont-trust-the-client/

**Comment by mike192020** [comment]
understandable that there will always be a way to view the url, but I just dont want to hand it to them, would rather make them work just a little. If you have any thoughts as to suppress it that would be great.

But there was still the issue of pdf's not downloading. do you happen to get this in your last push of the script?

On your dont trust the client. Believe me I do not really. I treat the client as if they have some knowledge on web development so I close those holes when I can. But then I am not a security expert and cannot get everything. Though that would be nice.

BTW I am in chrome.
