### ISSUE TITLE
Failed to load resource: Frame load interrupted (Safari OS X)

### ISSUE THREAD

**Issue by jeff-h** [johnculviner/jquery.fileDownload#99]
In Safari on OS X 10.10 I am getting the following error in the console, after my PDF has been generated and begins downloading:

`Failed to load resource: Frame load interrupted`

I don't get this in any other browser. I've messed around with my returned headers without any difference except if I remove:

```js
'Content-Disposition'           : 'attachment; filename="' + pdfFilename + '.pdf"',
```

...then the error goes away, but also my download doesn't happen.

**Comment by johnculviner** [comment]
Yeah I get that too on my mac here. Not sure, I bet Safari is getting confused. It's not really the best browser IMO for a lot of crappy nuances but at least its working. It works still so :neutral_face: Let me know if you find a way to get rid of the error and I can merge the PR. Thanks!

**Comment by borwahs** [comment]
I am running into the same issue. It does work though.

This might be related - https://bugs.webkit.org/show_bug.cgi?id=46491.

**Comment by johnculviner** [comment]
Thanks for the heads up! Yeah I think I'll leave the ticket it in this state unless it starts to cause actual problems.

**Comment by Anaphase** [comment]
If it's helpful, I'm also receiving this error when opening "direct download" links in Safari, and I'm not even using this library (in my case it's just an anchor tag linking to a direct download URL.) So it's likely just the bug outlined in @borwahs's link and nothing with this library.

**Comment by johnculviner** [comment]
:+1: Safari definitely is no fun on the fringes

**Comment by davidpelayo** [comment]
On latest stable release the HTML5 "download" attribute was implemented and, therefore, makes this works. [https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_1.html](https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Articles/Safari_10_1.html).
